# GBIF dataset

We have used the *EOD – eBird Observation Dataset* from GBIF, the Global Biodiversity Information Facility

In [2]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# loading EOD dataset
reading = pd.read_csv('gbif_eod.csv', 
                   sep = '\t', 
                   error_bad_lines = False)

In [4]:
# working with a copy
gbif = reading.copy()

In [5]:
# displaying all columns
pd.set_option('display.max_columns', None)
gbif.head()

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,infraspecificEpithet,taxonRank,scientificName,verbatimScientificName,verbatimScientificNameAuthorship,countryCode,locality,stateProvince,occurrenceStatus,individualCount,publishingOrgKey,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,coordinatePrecision,elevation,elevationAccuracy,depth,depthAccuracy,eventDate,day,month,year,taxonKey,speciesKey,basisOfRecord,institutionCode,collectionCode,catalogNumber,recordNumber,identifiedBy,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue
0,1787081975,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD_ESP:OBS478457128,Animalia,Chordata,Aves,Pelecaniformes,Ardeidae,Egretta,Egretta garzetta,NaN,SPECIES,"Egretta garzetta (Linnaeus, 1766)",Egretta garzetta,NaN,ES,Quinto T.M.,Aragón,PRESENT,20.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,41.428440,-0.502882,NaN,NaN,NaN,NaN,NaN,NaN,2012-03-03T00:00:00,3,3,2012,2480876,2480876,HUMAN_OBSERVATION,CLO,EBIRD_ESP,OBS478457128,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr884804,NaN,NaN,2021-06-16T14:27:54.852Z,NaN,NaN
1,2057171899,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS489292176,Animalia,Chordata,Aves,Phoenicopteriformes,Phoenicopteridae,Phoenicopterus,Phoenicopterus roseus,NaN,SPECIES,"Phoenicopterus roseus Pallas, 1811",Phoenicopterus roseus,NaN,ES,El Hondo PNat--Área General,Valenciana Comunidad,PRESENT,30.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,38.185850,-0.780973,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-23T00:00:00,23,4,2017,4352332,4352332,HUMAN_OBSERVATION,CLO,EBIRD,OBS489292176,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr424629,NaN,NaN,2021-06-16T14:27:59.243Z,NaN,COORDINATE_ROUNDED
2,2065545864,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS491474054,Animalia,Chordata,Aves,Passeriformes,Fringillidae,Chloris,Chloris chloris,NaN,SPECIES,"Chloris chloris (Linnaeus, 1758)",Chloris chloris,NaN,ES,"36,7155x-5,2412 - 28 Apr 2017, 20:58",Andalucía,PRESENT,1.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,36.715500,-5.241248,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-28T00:00:00,28,4,2017,5845582,5845582,HUMAN_OBSERVATION,CLO,EBIRD,OBS491474054,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr841249,NaN,NaN,2021-06-16T14:27:59.891Z,NaN,NaN
3,2099775253,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS559532012,Animalia,Chordata,Aves,Columbiformes,Columbidae,Columba,Columba livia,NaN,SPECIES,"Columba livia J.F.Gmelin, 1789",Columba livia,NaN,ES,Quintos de Mora,Castilla-La Mancha,PRESENT,NaN,e2e717bf-551a-4917-bdc9-4fa0f342c530,39.398663,-4.074597,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-15T00:00:00,15,11,2017,2495414,2495414,HUMAN_OBSERVATION,CLO,EBIRD,OBS559532012,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr825751,NaN,NaN,2021-06-16T14:28:31.288Z,NaN,COORDINATE_ROUNDED
4,2135744488,4fa7b334-ce0d-4e88-aaae-2e0c138d049e,URN:catalog:CLO:EBIRD:OBS588686591,Animalia,Chordata,Aves,Passeriformes,Aegithalidae,Aegithalos,Aegithalos caudatus,NaN,SPECIES,"Aegithalos caudatus (Linnaeus, 1758)",Aegithalos caudatus,NaN,ES,Valencia--Jardines del Turia,Valenciana Comunidad,PRESENT,4.0,e2e717bf-551a-4917-bdc9-4fa0f342c530,39.477215,-0.370145,NaN,NaN,NaN,NaN,NaN,NaN,2018-03-16T00:00:00,16,3,2018,2495000,2495000,HUMAN_OBSERVATION,CLO,EBIRD,OBS588686591,NaN,NaN,NaN,CC_BY_4_0,NaN,obsr534120,NaN,NaN,2021-06-16T14:28:43.256Z,NaN,COORDINATE_ROUNDED

There are some columns that don't give us relevant information: 
- gbifID
- datasetKey
- occurrenceID
- publishingOrgKey
- taxonKey
- speciesKey
- institutionCode
- collectionCode
- catalogNumber
- recordNumber
- identifiedBy
- dateIdentified
- license
- rightsHolder
- recordedBy
- typeStatus
- establishmentMeans
- lastInterpreted
- mediaType
- issue

We found some columns with one unique value, so we decided to drop them:
- kingdom
- phylum
- class
- taxonRank
- countryCode
- occurrenceStatus
- basisOfRecord

There are some columns with all non-value items: 
- infraspecificEpithet 
- verbatimScientificNameAuthorship
- coordinateUncertaintyInMeters
- coordinatePrecision
- elevation
- elevationAccuracy
- depth
- depthAccuracy

We decided to drop the scientific name and the verbatim scientific name and keep the specie, as both make reference to the same information
- scientificName
- verbatimScientificName

In [6]:
# dropping some columns 
to_drop = ['gbifID', 'datasetKey', 'occurrenceID', 'kingdom', 'phylum', 
           'class', 'infraspecificEpithet', 'taxonRank', 'scientificName',
           'verbatimScientificNameAuthorship', 'countryCode',
           'occurrenceStatus', 'publishingOrgKey', 'coordinateUncertaintyInMeters',
           'coordinatePrecision', 'elevation', 'elevationAccuracy', 'depth', 
           'depthAccuracy', 'taxonKey', 'speciesKey', 'basisOfRecord', 
           'institutionCode', 'collectionCode', 'catalogNumber', 'recordNumber',
           'identifiedBy', 'dateIdentified', 'license', 'rightsHolder','recordedBy',
           'typeStatus', 'establishmentMeans', 'verbatimScientificName',
           'lastInterpreted','mediaType', 'issue']
gbif.drop(to_drop, axis = 1, inplace = True)

In [7]:
# Now we have a 13 columns dataset
gbif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12382263 entries, 0 to 12382262
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   order             object
 1   family            object
 2   genus             object
 3   species           object
 4   locality          object
 5   stateProvince     object
 6   individualCount   float64
 7   decimalLatitude   float64
 8   decimalLongitude  float64
 9   eventDate         object
 10  day               int64
 11  month             int64
 12  year              int64
dtypes: float64(3), int64(3), object(7)
memory usage: 1.2+ GB

In [8]:
# setting an index for the dataset
gbif.index = [x for x in range(1, len(gbif.values)+1)]

In [9]:
gbif.isna().sum()

order                     0
family                    0
genus                     0
species                   0
locality                144
stateProvince             0
individualCount     1879095
decimalLatitude           0
decimalLongitude          0
eventDate                 0
day                       0
month                     0
year                      0
dtype: int64

In [10]:
# We assume that NaN values in the "individualCount" column means that there was only one specimen
gbif.individualCount = gbif.individualCount.replace(np.nan, '1')

In [11]:
# we change the individualCount values to an integer
gbif.individualCount = gbif.individualCount.astype(int)

In [12]:
# Reassigning the columns titles
gbif = gbif.rename(columns = {'decimalLatitude': 'lat',
                              'decimalLongitude': 'long',
                             'stateProvince': 'region',
                             'individualCount': 'observations'})

In [13]:
gbif.head()

,order,family,genus,species,locality,region,observations,lat,long,eventDate,day,month,year
1,Pelecaniformes,Ardeidae,Egretta,Egretta garzetta,Quinto T.M.,Aragón,20,41.428440,-0.502882,2012-03-03T00:00:00,3,3,2012
2,Phoenicopteriformes,Phoenicopteridae,Phoenicopterus,Phoenicopterus roseus,El Hondo PNat--Área General,Valenciana Comunidad,30,38.185850,-0.780973,2017-04-23T00:00:00,23,4,2017
3,Passeriformes,Fringillidae,Chloris,Chloris chloris,"36,7155x-5,2412 - 28 Apr 2017, 20:58",Andalucía,1,36.715500,-5.241248,2017-04-28T00:00:00,28,4,2017
4,Columbiformes,Columbidae,Columba,Columba livia,Quintos de Mora,Castilla-La Mancha,1,39.398663,-4.074597,2017-11-15T00:00:00,15,11,2017
5,Passeriformes,Aegithalidae,Aegithalos,Aegithalos caudatus,Valencia--Jardines del Turia,Valenciana Comunidad,4,39.477215,-0.370145,2018-03-16T00:00:00,16,3,2018

In [14]:
# checking unique values in order to confirm dataset is clean
print('Order: ', gbif.order.unique())
print('Family: ', gbif.family.unique())
print('Genus: ', gbif.genus.unique())
print('Specie: ', gbif.species.unique())
print('Latitude: ', gbif.lat.unique())
print('Longitude: ', gbif.long.unique())
print('Regions: ', gbif.region.unique())
print('Observations: ', gbif.observations.unique())
print('Family: ', gbif.family.unique())
print('Year: ', gbif.year.unique())
print('Month: ', gbif.month.unique())
print('Day: ', gbif.day.unique())

Order:  ['Pelecaniformes' 'Phoenicopteriformes' 'Passeriformes' 'Columbiformes'
 'Charadriiformes' 'Podicipediformes' 'Anseriformes' 'Ciconiiformes'
 'Accipitriformes' 'Gruiformes' 'Bucerotiformes' 'Cuculiformes'
 'Suliformes' 'Apodiformes' 'Falconiformes' 'Psittaciformes'
 'Coraciiformes' 'Strigiformes' 'Piciformes' 'Galliformes' 'Otidiformes'
 'Procellariiformes' 'Pteroclidiformes' 'Caprimulgiformes' 'Gaviiformes'
 'Phaethontiformes']
Family:  ['Ardeidae' 'Phoenicopteridae' 'Fringillidae' 'Columbidae' 'Aegithalidae'
 'Hirundinidae' 'Laniidae' 'Laridae' 'Podicipedidae' 'Anatidae' 'Corvidae'
 'Scolopacidae' 'Ciconiidae' 'Muscicapidae' 'Remizidae' 'Accipitridae'
 'Motacillidae' 'Sylviidae' 'Passeridae' 'Rallidae' 'Upupidae'
 'Phylloscopidae' 'Sturnidae' 'Regulidae' 'Cinclidae' 'Troglodytidae'
 'Cuculidae' 'Turdidae' 'Prunellidae' 'Paridae' 'Threskiornithidae'
 'Cisticolidae' 'Cettiidae' 'Charadriidae' 'Certhiidae' 'Oriolidae'
 'Acrocephalidae' 'Phalacrocoracidae' 'Apodidae' 'Falconidae'
 'Psittacidae' 'Alaudidae' 'Pycnonotidae' 'Alcedinidae' 'Emberizidae'
 'Meropidae' 'Recurvirostridae' 'Strigidae' 'Gruidae' 'Sittidae' 'Picidae'
 'Phasianidae' 'Estrildidae' 'Burhinidae' 'Otididae' 'Haematopodidae'
 'Procellariidae' 'Glareolidae' 'Coraciidae' 'Pteroclididae' 'Pandionidae'
 'Alcidae' 'Caprimulgidae' 'Hydrobatidae' 'Sulidae' 'Calcariidae'
 'Panuridae' 'Ploceidae' 'Gaviidae' 'Locustellidae' 'Tytonidae'
 'Stercorariidae' 'Tichodromidae' 'Leiothrichidae' 'Malaconotidae'
 'Bombycillidae' 'Pelecanidae' 'Phaethontidae' 'Mimidae' 'Icteridae'
 'Diomedeidae' 'Fregatidae' 'Vireonidae' 'Viduidae' 'Jacanidae'
 'Pluvianidae']
Genus:  ['Egretta' 'Phoenicopterus' 'Chloris' 'Columba' 'Aegithalos' 'Hirundo'
 'Lanius' 'Larus' 'Tachybaptus' 'Anser' 'Corvus' 'Calidris' 'Pica'
 'Ciconia' 'Oenanthe' 'Remiz' 'Coloeus' 'Gallinago' 'Pyrrhula' 'Neophron'
 'Circus' 'Motacilla' 'Phoenicurus' 'Sylvia' 'Luscinia' 'Passer'
 'Delichon' 'Fulica' 'Upupa' 'Ardea' 'Phylloscopus' 'Podiceps' 'Sturnus'
 'Phoeniconaias' 'Muscicapa' 'Regulus' 'Anas' 'Cinclus' 'Pernis'
 'Garrulus' 'Troglodytes' 'Erithacus' 'Cuculus' 'Turdus' 'Prunella'
 'Parus' 'Milvus' 'Platalea' 'Saxicola' 'Tadorna' 'Cisticola' 'Cettia'
 'Charadrius' 'Certhia' 'Bubulcus' 'Tringa' 'Gyps' 'Oriolus' 'Hippolais'
 'Phalacrocorax' 'Fringilla' 'Ptyonoprogne' 'Apus' 'Buteo' 'Streptopelia'
 'Falco' 'Periparus' 'Numenius' 'Petronia' 'Aratinga' 'Anthus' 'Alauda'
 'Galerida' 'Pycnonotus' 'Alcedo' 'Calandrella' 'Emberiza' 'Carduelis'
 'Ixobrychus' 'Monticola' 'Merops' 'Rallus' 'Himantopus' 'Otus'
 'Chroicocephalus' 'Riparia' 'Cyanistes' 'Lophophanes' 'Linaria' 'Aquila'
 'Serinus' 'Grus' 'Thalasseus' 'Aythya' 'Gypaetus' 'Accipiter'
 'Hieraaetus' 'Netta' 'Pluvialis' 'Athene' 'Nycticorax' 'Circaetus'
 'Sitta' 'Ficedula' 'Picus' 'Gallinula' 'Melanocorypha' 'Vanellus'
 'Marmaronetta' 'Elanus' 'Alectoris' 'Estrilda' 'Acrocephalus' 'Spinus'
 'Cecropis' 'Actitis' 'Burhinus' 'Limosa' 'Philomachus' 'Tetrax'
 'Haematopus' 'Myiopsitta' 'Erythropygia' 'Puffinus' 'Otis' 'Lullula'
 'Porphyrio' 'Rissa' 'Bucanetes' 'Gelochelidon' 'Dendrocopos' 'Glareola'
 'Cygnus' 'Coracias' 'Pterocles' 'Pandion' 'Alopochen' 'Pyrrhocorax'
 'Plegadis' 'Botaurus' 'Alca' 'Clamator' 'Recurvirostra' 'Caprimulgus'
 'Sternula' 'Aegypius' 'Hydrobates' 'Asio' 'Mergus' 'Ichthyaetus'
 'Melanitta' 'Porzana' 'Jynx' 'Coturnix' 'Poecile' 'Arenaria' 'Morus'
 'Cyanopica' 'Plectrophenax' 'Oxyura' 'Ardeola' 'Hydroprogne' 'Strix'
 'Loxia' 'Panurus' 'Sterna' 'Psittacula' 'Chlidonias' 'Ploceus'
 'Tryngites' 'Coccothraustes' 'Calonectris' 'Bubo' 'Gavia' 'Phasianus'
 'Amandava' 'Dryocopus' 'Locustella' 'Tyto' 'Hydrocoloeus' 'Stercorarius'
 'Iduna' 'Cursorius' 'Lymnocryptes' 'Montifringilla' 'Somateria' 'Branta'
 'Chersophilus' 'Leucophaeus' 'Tichodroma' 'Oceanites' 'Fratercula'
 'Xenus' 'Haemorhous' 'Clangula' 'Uria' 'Lophodytes' 'Spilopelia'
 'Leiothrix' 'Pionus' 'Oceanodroma' 'Tchagra' 'Geronticus' 'Chlamydotis'
 'Phalaropus' 'Bucephala' 'Threskiornis' 'Euplectes' 'Fulmarus' 'Scolopax'
 'Agapornis' 'Xema' 'Perdix' 'Podilymbus' 'Quelea' 'Bombycilla' 'Alle'
 'Calcarius' 'Aix' 'Pastor' 'Limnodromus' 'Bulweria' 'Sula' 'Acanthis'
 'Acridotheres' 'Aegolius' 'Chen' 'Parabuteo' 'Mergellus' 'Cairina'
 'Poicephalus' 'Fregetta' 'Carpodacus' 'Pelagodroma' 'Crex'
 'Aenigmatolimnas' 'Haliaeetus' 'Nandayus' 'Pelecanus' 'Dendrocygna'
 'Phaethon' 'Limicola' 'Taeniopygia' 'Leptoptilos' 'Cepphus' 'Bartramia'
 'Pterodroma' 'Megaceryle' 'Nymphicus' 'Rhodostethia' 'Chaetura'
 'Eremophila' 'Tarsiger' 'Mycteria' 'Amazona' 'Lonchura' 'Anthropoides'
 'Mimus' 'Dolichonyx' 'Thalassarche' 'Bostrychia' 'Aramides' 'Ammomanes'
 'Lagopus' 'Zenaida' 'Callonetta' 'Terathopius' 'Alaemon' 'Onychoprion'
 'Fregata' 'Cyanoliseus' 'Chordeiles' 'Melopsittacus' 'Vireo' 'Euodice'
 'Vidua' 'Actophilornis' 'Lamprotornis' 'Pluvianus' 'Nucifraga'
 'Quiscalus' 'Rhodospiza' 'Geranoaetus']
Specie:  ['Egretta garzetta' 'Phoenicopterus roseus' 'Chloris chloris'
 'Columba livia' 'Aegithalos caudatus' 'Hirundo rustica'
 'Lanius meridionalis' 'Larus michahellis' 'Tachybaptus ruficollis'
 'Anser anser' 'Corvus corone' 'Calidris alba' 'Pica pica'
 'Ciconia ciconia' 'Oenanthe oenanthe' 'Remiz pendulinus'
 'Coloeus monedula' 'Gallinago gallinago' 'Pyrrhula pyrrhula'
 'Neophron percnopterus' 'Circus aeruginosus' 'Motacilla flava'
 'Phoenicurus ochruros' 'Sylvia atricapilla' 'Luscinia megarhynchos'
 'Passer domesticus' 'Delichon urbicum' 'Fulica atra' 'Upupa epops'
 'Ardea cinerea' 'Phylloscopus collybita' 'Corvus corax'
 'Podiceps nigricollis' 'Columba palumbus' 'Sturnus unicolor'
 'Phoeniconaias minor' 'Muscicapa striata' 'Regulus ignicapilla'
 'Anas platyrhynchos' 'Cinclus cinclus' 'Pernis apivorus'
 'Garrulus glandarius' 'Phoenicurus phoenicurus' 'Troglodytes troglodytes'
 'Erithacus rubecula' 'Cuculus canorus' 'Turdus viscivorus'
 'Prunella modularis' 'Parus major' 'Milvus migrans' 'Platalea leucorodia'
 'Saxicola rubicola' 'Tadorna ferruginea' 'Passer montanus'
 'Cisticola juncidis' 'Cettia cetti' 'Charadrius dubius'
 'Certhia brachydactyla' 'Bubulcus ibis' 'Tringa totanus' 'Gyps fulvus'
 'Turdus merula' 'Oriolus oriolus' 'Hippolais polyglotta'
 'Phalacrocorax carbo' 'Fringilla coelebs' 'Ptyonoprogne rupestris'
 'Apus pallidus' 'Buteo buteo' 'Motacilla alba' 'Streptopelia decaocto'
 'Falco peregrinus' 'Periparus ater' 'Numenius phaeopus'
 'Petronia petronia' 'Aratinga erythrogenys' 'Anthus campestris'
 'Alauda arvensis' 'Anthus pratensis' 'Anas crecca'
 'Charadrius alexandrinus' 'Galerida cristata' 'Pycnonotus barbatus'
 'Sylvia communis' 'Alcedo atthis' 'Saxicola rubetra'
 'Calandrella brachydactyla' 'Emberiza calandra' 'Carduelis carduelis'
 'Phylloscopus trochilus' 'Ixobrychus minutus' 'Monticola solitarius'
 'Tringa erythropus' 'Sturnus vulgaris' 'Merops apiaster' 'Apus apus'
 'Rallus aquaticus' 'Passer hispaniolensis' 'Himantopus himantopus'
 'Phylloscopus canariensis' 'Milvus milvus' 'Otus scops'
 'Chroicocephalus ridibundus' 'Riparia riparia' 'Cyanistes caeruleus'
 'Lophophanes cristatus' 'Linaria cannabina' 'Podiceps cristatus'
 'Anas strepera' 'Aquila chrysaetos' 'Anas clypeata' 'Serinus serinus'
 'Galerida theklae' 'Sylvia cantillans' 'Emberiza schoeniclus' 'Grus grus'
 'Thalasseus sandvicensis' 'Sylvia melanocephala' 'Aythya ferina'
 'Emberiza cirlus' 'Gypaetus barbatus' 'Calidris canutus'
 'Accipiter nisus' 'Accipiter gentilis' 'Larus cachinnans'
 'Hieraaetus pennatus' 'Netta rufina' 'Pluvialis apricaria'
 'Athene noctua' 'Nycticorax nycticorax' 'Turdus pilaris'
 'Circaetus gallicus' 'Sitta europaea' 'Ciconia nigra' 'Calidris alpina'
 'Tadorna tadorna' 'Columba oenas' 'Ficedula hypoleuca'
 'Podiceps grisegena' 'Motacilla cinerea' 'Apus affinis' 'Picus viridis'
 'Falco subbuteo' 'Gallinula chloropus' 'Melanocorypha calandra'
 'Ardea purpurea' 'Falco tinnunculus' 'Vanellus vanellus'
 'Marmaronetta angustirostris' 'Elanus caeruleus' 'Calidris minuta'
 'Alectoris rufa' 'Estrilda astrild' 'Acrocephalus arundinaceus'
 'Turdus philomelos' 'Lanius senator' 'Spinus spinus' 'Cecropis daurica'
 'Fulica cristata' 'Actitis hypoleucos' 'Burhinus oedicnemus'
 'Limosa limosa' 'Ardea alba' 'Philomachus pugnax' 'Tetrax tetrax'
 'Haematopus ostralegus' 'Phylloscopus ibericus' 'Anas penelope'
 'Myiopsitta monachus' 'Erythropygia galactotes' 'Emberiza cia'
 'Phylloscopus sibillatrix' 'Turdus iliacus' 'Circus pygargus'
 'Phylloscopus bonelli' 'Puffinus mauretanicus' 'Otis tarda'
 'Tringa ochropus' 'Anas acuta' 'Lanius collurio' 'Numenius arquata'
 'Limosa lapponica' 'Falco naumanni' 'Charadrius hiaticula' 'Apus melba'
 'Lullula arborea' 'Anthus spinoletta' 'Larus fuscus'
 'Porphyrio porphyrio' 'Anthus trivialis' 'Oenanthe leucura'
 'Rissa tridactyla' 'Bucanetes githagineus' 'Streptopelia turtur'
 'Acrocephalus schoenobaenus' 'Gelochelidon nilotica' 'Dendrocopos major'
 'Serinus canaria' 'Glareola pratincola' 'Cygnus olor' 'Aythya nyroca'
 'Coracias garrulus' 'Corvus cornix' 'Pterocles alchata'
 'Pandion haliaetus' 'Alopochen aegyptiaca' 'Acrocephalus scirpaceus'
 'Tringa nebularia' 'Pyrrhocorax pyrrhocorax' 'Plegadis falcinellus'
 'Botaurus stellaris' 'Circus cyaneus' 'Emberiza citrinella' 'Alca torda'
 'Prunella collaris' 'Clamator glandarius' 'Aquila fasciata'
 'Recurvirostra avosetta' 'Caprimulgus ruficollis' 'Anthus berthelotii'
 'Sternula albifrons' 'Aegypius monachus' 'Hydrobates pelagicus'
 'Asio otus' 'Calidris ferruginea' 'Larus marinus' 'Mergus serrator'
 'Sylvia borin' 'Apus unicolor' 'Ichthyaetus melanocephalus'
 'Puffinus griseus' 'Luscinia svecica' 'Melanitta nigra' 'Tringa glareola'
 'Porzana porzana' 'Jynx torquilla' 'Pluvialis squatarola' 'Larus canus'
 'Puffinus puffinus' 'Fringilla montifringilla' 'Calandrella rufescens'
 'Coturnix coturnix' 'Puffinus yelkouan' 'Poecile palustris'
 'Oenanthe hispanica' 'Anas querquedula' 'Arenaria interpres'
 'Ichthyaetus audouinii' 'Morus bassanus' 'Cyanopica cooki'
 'Chroicocephalus genei' 'Monticola saxatilis' 'Plectrophenax nivalis'
 'Oxyura leucocephala' 'Sylvia undata' 'Ardeola ralloides'
 'Saxicola dacotiae' 'Hydroprogne caspia' 'Strix aluco'
 'Sylvia conspicillata' 'Phalacrocorax aristotelis' 'Carduelis citrinella'
 'Turdus torquatus' 'Loxia curvirostra' 'Aquila adalberti'
 'Lanius excubitor' 'Sylvia hortensis' 'Panurus biarmicus'
 'Sterna hirundo' 'Psittacula krameri' 'Pterocles orientalis'
 'Cygnus atratus' 'Acrocephalus melanopogon' 'Chlidonias niger'
 'Ploceus melanocephalus' 'Aythya fuligula' 'Tryngites subruficollis'
 'Coccothraustes coccothraustes' 'Chroicocephalus philadelphia'
 'Dendrocopos minor' 'Falco columbarius' 'Chlidonias hybrida'
 'Calonectris diomedea' 'Bubo bubo' 'Asio flammeus' 'Gavia stellata'
 'Certhia familiaris' 'Phasianus colchicus' 'Amandava amandava'
 'Anas discors' 'Aythya marila' 'Fringilla teydea' 'Dryocopus martius'
 'Emberiza hortulana' 'Anser albifrons' 'Locustella luscinioides'
 'Regulus regulus' 'Alectoris barbara' 'Tyto alba' 'Podiceps auritus'
 'Cyanistes teneriffae' 'Hydrocoloeus minutus' 'Stercorarius parasiticus'
 'Calidris temminckii' 'Iduna opaca' 'Locustella naevia'
 'Cursorius cursor' 'Lymnocryptes minimus' 'Streptopelia roseogrisea'
 'Montifringilla nivalis' 'Sterna paradisaea' 'Caprimulgus europaeus'
 'Stercorarius skua' 'Gavia immer' 'Chlidonias leucopterus'
 'Porphyrio alleni' 'Somateria mollissima' 'Calidris melanotos'
 'Larus argentatus' 'Branta bernicla' 'Sterna dougallii'
 'Chersophilus duponti' 'Leucophaeus pipixcan' 'Anser brachyrhynchus'
 'Melanitta fusca' 'Tichodroma muraria' 'Sylvia balearica'
 'Phylloscopus inornatus' 'Branta leucopsis' 'Oceanites oceanicus'
 'Thalasseus elegans' 'Porzana parva' 'Charadrius morinellus'
 'Anser serrirostris' 'Leucophaeus atricilla' 'Fratercula arctica'
 'Xenus cinereus' 'Puffinus gravis' 'Haemorhous mexicanus'
 'Pyrrhocorax graculus' 'Clangula hyemalis' 'Aythya collaris'
 'Apus caffer' 'Gyps rueppellii' 'Corvus frugilegus' 'Pycnonotus jocosus'
 'Dendrocopos medius' 'Uria aalge' 'Tringa stagnatilis'
 'Oenanthe isabellina' 'Stercorarius longicaudus' 'Lophodytes cucullatus'
 'Cygnus cygnus' 'Aquila clanga' 'Spilopelia senegalensis'
 'Leiothrix lutea' 'Pionus maximiliani' 'Estrilda troglodytes'
 'Larus glaucoides' 'Egretta gularis' 'Anthus petrosus' 'Gavia arctica'
 'Oceanodroma leucorhoa' 'Tchagra senegalus' 'Geronticus eremita'
 'Buteo rufinus' 'Chlamydotis undulata' 'Phalaropus lobatus'
 'Falco eleonorae' 'Falco vespertinus' 'Anser indicus' 'Porzana pusilla'
 'Emberiza pusilla' 'Stercorarius pomarinus' 'Bucephala clangula'
 'Circus macrourus' 'Threskiornis aethiopicus' 'Anthus richardi'
 'Anthus cervinus' 'Lanius isabellinus' 'Phalaropus fulicarius'
 'Hippolais icterina' 'Anser erythropus' 'Tringa flavipes'
 'Euplectes afer' 'Ficedula albicollis' 'Fulmarus glacialis'
 'Scolopax rusticola' 'Columba bollii' 'Ixobrychus sturmii'
 'Agapornis roseicollis' 'Vanellus gregarius' 'Anas americana'
 'Phylloscopus humei' 'Xema sabini' 'Columba junoniae' 'Perdix perdix'
 'Mergus merganser' 'Pluvialis dominica' 'Larus delawarensis'
 'Thalasseus bengalensis' 'Fulica americana' 'Larus hyperboreus'
 'Podilymbus podiceps' 'Aratinga mitrata' 'Ichthyaetus ichthyaetus'
 'Puffinus baroli' 'Aythya affinis' 'Dendrocopos leucotos' 'Quelea quelea'
 'Bombycilla garrulus' 'Motacilla citreola' 'Alle alle' 'Sylvia subalpina'
 'Calcarius lapponicus' 'Oenanthe deserti' 'Calidris maritima'
 'Merops persicus' 'Aix galericulata' 'Acrocephalus paludicola'
 'Pastor roseus' 'Corvus ruficollis' 'Charadrius semipalmatus'
 'Limnodromus scolopaceus' 'Cygnus columbianus' 'Emberiza sahari'
 'Bulweria bulwerii' 'Oceanodroma castro' 'Calidris minutilla'
 'Aratinga acuticaudata' 'Sula sula' 'Pycnonotus cafer' 'Pluvialis fulva'
 'Branta ruficollis' 'Acanthis flammea' 'Acridotheres tristis'
 'Aegolius funereus' 'Sylvia curruca' 'Psittacula eupatria'
 'Chen caerulescens' 'Parabuteo unicinctus' 'Mergellus albellus'
 'Calidris fuscicollis' 'Cairina moschata' 'Gavia pacifica'
 'Poicephalus senegalus' 'Oxyura jamaicensis' 'Fregetta tropica'
 'Oceanodroma monorhis' 'Calidris bairdii' 'Anas formosa'
 'Carpodacus erythrinus' 'Phalaropus tricolor' 'Pelagodroma marina'
 'Crex crex' 'Platalea alba' 'Aenigmatolimnas marginalis'
 'Branta canadensis' 'Haliaeetus albicilla' 'Nandayus nenday'
 'Anthus hodgsoni' 'Corvus albus' 'Turdus obscurus' 'Charadrius vociferus'
 'Anser fabalis' 'Pelecanus rufescens' 'Dendrocygna autumnalis'
 'Anas sibilatrix' 'Picus vaillantii' 'Actitis macularius'
 'Anthus rubescens' 'Lanius cristatus' 'Phoenicopterus chilensis'
 'Acrocephalus baeticatus' 'Saxicola maurus' 'Aquila pomarina'
 'Phaethon aethereus' 'Charadrius leschenaultii' 'Melanitta perspicillata'
 'Limicola falcinellus' 'Passer italiae' 'Taeniopygia guttata'
 'Pelecanus onocrotalus' 'Phoenicopterus ruber' 'Gallinago media'
 'Leptoptilos crumenifer' 'Estrilda melpoda' 'Emberiza leucocephalos'
 'Emberiza melanocephala' 'Stercorarius maccormicki' 'Cepphus grylle'
 'Bartramia longicauda' 'Sterna forsteri' 'Sylvia nisoria' 'Anas rubripes'
 'Phylloscopus fuscatus' 'Pterodroma feae' 'Megaceryle alcyon'
 'Calidris pusilla' 'Larus dominicanus' 'Aix sponsa'
 'Nymphicus hollandicus' 'Rhodostethia rosea' 'Limnodromus griseus'
 'Agapornis fischeri' 'Thalasseus maximus' 'Aquila nipalensis'
 'Pterodroma macroptera' 'Coracias abyssinicus' 'Chaetura pelagica'
 'Bucephala albeola' 'Eremophila alpestris' 'Tarsiger cyanurus'
 'Phylloscopus proregulus' 'Sula leucogaster' 'Mycteria ibis'
 'Amazona aestiva' 'Ficedula parva' 'Lonchura punctulata'
 'Phalacrocorax pygmaeus' 'Anthropoides virgo' 'Amazona ochrocephala'
 'Agapornis personatus' 'Somateria spectabilis' 'Pelecanus crispus'
 'Mimus polyglottos' 'Turdus migratorius' 'Acrocephalus agricola'
 'Mimus gilvus' 'Grus canadensis' 'Falco sparverius'
 'Dolichonyx oryzivorus' 'Thalassarche melanophris' 'Bostrychia hagedash'
 'Phoenicurus moussieri' 'Egretta tricolor' 'Acrocephalus dumetorum'
 'Anas bahamensis' 'Calidris tenuirostris' 'Thalassarche chlororhynchos'
 'Aquila heliaca' 'Lanius nubicus' 'Aramides ypecaha' 'Emberiza aureola'
 'Passer luteus' 'Ammomanes cinctura' 'Lagopus lagopus' 'Pica mauritanica'
 'Zenaida macroura' 'Callonetta leucophrys' 'Corvus splendens'
 'Chroicocephalus cirrocephalus' 'Branta hutchinsii' 'Tringa solitaria'
 'Anas georgica' 'Tringa melanoleuca' 'Locustella fluviatilis'
 'Anas cyanoptera' 'Terathopius ecaudatus' 'Sylvia deserticola'
 'Alaemon alaudipes' 'Motacilla tschutschensis' 'Sylvia sarda'
 'Turdus naumanni' 'Anthus godlewskii' 'Porphyrio martinica'
 'Onychoprion fuscatus' 'Emberiza rustica' 'Fregata magnificens'
 'Buteo lagopus' 'Cyanoliseus patagonus' 'Bubo ascalaphus'
 'Chordeiles minor' 'Melopsittacus undulatus' 'Vireo olivaceus'
 'Psittacula cyanocephala' 'Gyps africanus' 'Euodice cantans'
 'Calidris acuminata' 'Dendrocygna bicolor' 'Iduna pallida'
 'Phylloscopus schwarzi' 'Amazona amazonica' 'Sylvia deserti'
 'Onychoprion anaethetus' 'Vidua macroura' 'Melanocorypha bimaculata'
 'Actophilornis africanus' 'Falco amurensis' 'Lamprotornis caudatus'
 'Linaria flavirostris' 'Pluvianus aegyptius' 'Nucifraga caryocatactes'
 'Euplectes orix' 'Acrocephalus palustris' 'Lamprotornis chalybaeus'
 'Ploceus cucullatus' 'Acridotheres cristatellus' 'Quiscalus mexicanus'
 'Crex egregia' 'Rhodospiza obsoleta' 'Sylvia nana' 'Sula dactylatra'
 'Puffinus boydi' 'Charadrius pecuarius' 'Pionus menstruus' 'Lanius minor'
 'Emberiza cioides' 'Lamprotornis unicolor' 'Gallinago delicata'
 'Geranoaetus melanoleucus']

Latitude:  [41.42844  38.18585  36.7155   ... 42.364483 40.440502 41.97548 ]
Longitude:  [-0.502882 -0.780973 -5.241248 ... -7.433391 -3.704359 -6.14086 ]
Regions:  ['Aragón' 'Valenciana Comunidad' 'Andalucía' 'Castilla-La Mancha'
 'Cataluña' 'Extremadura' 'Illes Baleares' 'País Vasco' 'Castilla y León'
 'Cantabria' 'Asturias Principado de' 'Madrid Comunidad de'
 'Navarra Comunidad Foral de' 'Galicia' 'Ceuta' 'Murcia Región de'
 'Canarias' 'La Rioja' 'Melilla']
Observations:  [  20   30    1 ... 6195 3045 3665]
Family:  ['Ardeidae' 'Phoenicopteridae' 'Fringillidae' 'Columbidae' 'Aegithalidae'
 'Hirundinidae' 'Laniidae' 'Laridae' 'Podicipedidae' 'Anatidae' 'Corvidae'
 'Scolopacidae' 'Ciconiidae' 'Muscicapidae' 'Remizidae' 'Accipitridae'
 'Motacillidae' 'Sylviidae' 'Passeridae' 'Rallidae' 'Upupidae'
 'Phylloscopidae' 'Sturnidae' 'Regulidae' 'Cinclidae' 'Troglodytidae'
 'Cuculidae' 'Turdidae' 'Prunellidae' 'Paridae' 'Threskiornithidae'
 'Cisticolidae' 'Cettiidae' 'Charadriidae' 'Certhiidae' 'Oriolidae'
 'Acrocephalidae' 'Phalacrocoracidae' 'Apodidae' 'Falconidae'
 'Psittacidae' 'Alaudidae' 'Pycnonotidae' 'Alcedinidae' 'Emberizidae'
 'Meropidae' 'Recurvirostridae' 'Strigidae' 'Gruidae' 'Sittidae' 'Picidae'
 'Phasianidae' 'Estrildidae' 'Burhinidae' 'Otididae' 'Haematopodidae'
 'Procellariidae' 'Glareolidae' 'Coraciidae' 'Pteroclididae' 'Pandionidae'
 'Alcidae' 'Caprimulgidae' 'Hydrobatidae' 'Sulidae' 'Calcariidae'
 'Panuridae' 'Ploceidae' 'Gaviidae' 'Locustellidae' 'Tytonidae'
 'Stercorariidae' 'Tichodromidae' 'Leiothrichidae' 'Malaconotidae'
 'Bombycillidae' 'Pelecanidae' 'Phaethontidae' 'Mimidae' 'Icteridae'
 'Diomedeidae' 'Fregatidae' 'Vireonidae' 'Viduidae' 'Jacanidae'
 'Pluvianidae']
Year:  [2012 2017 2018 2019 2020 2006 1997 2015 2016 2010 2008 2005 2014 2009
 1995 2004 2011 2002 1998 1999 2000 2013 1991 2007 1984 2001 1994 2003
 1983 1985 1969 1996 1982 1971 1987 1993 1981 1990 1992 1988 1974 1989
 1986 1964 1978 1979 1980 1976 1973 1972 1977 1967 1955 1965 1968 1975
 1970 1938 1937 1966 1942 1905 1957 1958 1900 1935 1954 1940 1963 1931
 1960 1936 1939 1932 1943 1924 1941 1934 1959 1933 1901 1944 1952 1945
 1872 1949 1956]
Month:  [ 3  4 11  7  8  9 12  5  2  1 10  6]
Day:  [ 3 23 28 15 16 19 14  9 26 29 17 25 24  5 11 21 10 22  7 18  2 12 30 31
  6 13  8 20  1  4 27]

In [15]:
# Dictionaty to change regions names
regions_dict = {'Valenciana Comunidad': 'Valencia',
 'Illes Baleares': 'Islas Baleares',
 'Asturias Principado de': 'Asturias',
 'Madrid Comunidad de': 'Madrid',
 'Navarra Comunidad Foral de': 'Navarra',
 'Murcia Región de': 'Murcia'}

In [16]:
# Replacing regions names
gbif['region'].replace(regions_dict, inplace = True)
gbif.region.unique()

array(['Aragón', 'Valencia', 'Andalucía', 'Castilla-La Mancha',
       'Cataluña', 'Extremadura', 'Islas Baleares', 'País Vasco',
       'Castilla y León', 'Cantabria', 'Asturias', 'Madrid', 'Navarra',
       'Galicia', 'Ceuta', 'Murcia', 'Canarias', 'La Rioja', 'Melilla'],
      dtype=object)

In [17]:
# checking the observations values
obs = np.sort(gbif.observations.unique())
print(len(obs))
obs[2600:]

2646

array([  20000,   21000,   21596,   21760,   22000,   23000,   23011,
         23100,   23600,   23800,   24000,   25000,   26000,   27000,
         27112,   27284,   28000,   30000,   31253,   33000,   35000,
         37000,   40000,   41500,   44000,   45000,   45390,   50000,
         50200,   55000,   56430,   60000,   75000,   80000,  100000,
        150000,  200000,  250000,  295000,  300000,  400000,  434508,
        500000,  800000, 1000000, 2000000])

In [18]:
gbif.to_csv('gbif.csv')

In [19]:
gbif_r = gbif[(gbif['year'] > 2000) & (gbif['year'] <= 2020)]
gbif_r.to_csv('gbif_r.csv')

In [20]:
gbif20 = gbif[gbif['year'] == 2020]
gbif20.to_csv('gbif20.csv')